name: Friday Night Funkin Compiling
run-name: Compiling Friday Night Funkin...

on: [ push, pull_request, workflow_dispatch ]
    
jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v4
      - name: Download Submodules
        run: git submodule update --init --recursive
      - name: Setup Haxe environment
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Download HMM
        run: haxelib install --quiet hmm
      - name: Use HMM to install dependencies.
        run: |
            cd ${{ github.workspace }}
            haxelib run hmm install -q
      - name: Compile The Game
        run: haxelib run lime build windows
      - name: Upload Game Executable
        uses: actions/upload-artifact@v4
        with:
          name: WindowsGame
          path: ${{ github.workspace }}/export/release/windows/bin/
  Linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Download Repository
        uses: actions/checkout@v4
      - name: Download Submodules
        run: git submodule update --init --recursive
      - name: Setup Haxe environment
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install Linux dependencies.
        run: |
            sudo apt update
            sudo apt install libvlc-dev libvlccore-dev vlc-bin vlc libc6 libc6-dev -y
      - name: Download HMM
        run: haxelib install --quiet hmm
      - name: Use HMM to install dependencies.
        run: |
            cd ${{ github.workspace }}
            haxelib run hmm install -q
      - name: Compile The Game
        run: haxelib run lime build linux
      - name: Wait for 1.5 seconds
        run: sleep 1.5
      - name: Upload Game Executable
        uses: actions/upload-artifact@v4
        with:
          name: LinuxGame
          path: ${{ github.workspace }}/export/release/linux/bin/
  MacOS:
    runs-on: macos-12
    steps:
      - name: Download Repository
        uses: actions/checkout@v4
      - name: Download Submodules
        run: git submodule update --init --recursive
      - name: Setup Haxe environment
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Download HMM
        run: haxelib install --quiet hmm
      - name: Use HMM to install dependencies.
        run: |
            cd ${{ github.workspace }}
            haxelib run hmm install -q
      - name: Compile The Game
        run: haxelib run lime build mac
      - name: Wait for 1.5 seconds
        run: sleep 1.5
      - name: Upload Game Executable
        uses: actions/upload-artifact@v4
        with:
          name: MacOSGame
          path: ${{ github.workspace }}/export/release/macos/bin/
