name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: "Deploy the Funkin' Website"
    runs-on: ubuntu-latest

    steps:
      - name: Download Source Code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Haxe Libraries using HMM
        run: |
          haxelib install hmm --quiet
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib run hmm install --quiet

      - name: Compile Application
        run: haxelib run lime build html5

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "./export/release/html5/bin/"

      - name: Deploy Website
        id: deployment
        uses: actions/deploy-pages@v4.0.5
